# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/navin/repos/perf-test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/navin/repos/perf-test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/navin/repos/perf-test/CMakeFiles /home/navin/repos/perf-test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/navin/repos/perf-test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named perftest

# Build rule for target.
perftest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perftest
.PHONY : perftest

# fast build rule for target.
perftest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perftest.dir/build.make CMakeFiles/perftest.dir/build
.PHONY : perftest/fast

#=============================================================================
# Target rules for targets named SimpleDB

# Build rule for target.
SimpleDB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleDB
.PHONY : SimpleDB

# fast build rule for target.
SimpleDB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDB.dir/build.make CMakeFiles/SimpleDB.dir/build
.PHONY : SimpleDB/fast

#=============================================================================
# Target rules for targets named floatfuncs

# Build rule for target.
floatfuncs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 floatfuncs
.PHONY : floatfuncs

# fast build rule for target.
floatfuncs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/build
.PHONY : floatfuncs/fast

src/SimpleDB/simpledb.o: src/SimpleDB/simpledb.c.o
.PHONY : src/SimpleDB/simpledb.o

# target to build an object file
src/SimpleDB/simpledb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDB.dir/build.make CMakeFiles/SimpleDB.dir/src/SimpleDB/simpledb.c.o
.PHONY : src/SimpleDB/simpledb.c.o

src/SimpleDB/simpledb.i: src/SimpleDB/simpledb.c.i
.PHONY : src/SimpleDB/simpledb.i

# target to preprocess a source file
src/SimpleDB/simpledb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDB.dir/build.make CMakeFiles/SimpleDB.dir/src/SimpleDB/simpledb.c.i
.PHONY : src/SimpleDB/simpledb.c.i

src/SimpleDB/simpledb.s: src/SimpleDB/simpledb.c.s
.PHONY : src/SimpleDB/simpledb.s

# target to generate assembly for a file
src/SimpleDB/simpledb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDB.dir/build.make CMakeFiles/SimpleDB.dir/src/SimpleDB/simpledb.c.s
.PHONY : src/SimpleDB/simpledb.c.s

src/floatfuncs/FLOPanalyzer.o: src/floatfuncs/FLOPanalyzer.c.o
.PHONY : src/floatfuncs/FLOPanalyzer.o

# target to build an object file
src/floatfuncs/FLOPanalyzer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/FLOPanalyzer.c.o
.PHONY : src/floatfuncs/FLOPanalyzer.c.o

src/floatfuncs/FLOPanalyzer.i: src/floatfuncs/FLOPanalyzer.c.i
.PHONY : src/floatfuncs/FLOPanalyzer.i

# target to preprocess a source file
src/floatfuncs/FLOPanalyzer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/FLOPanalyzer.c.i
.PHONY : src/floatfuncs/FLOPanalyzer.c.i

src/floatfuncs/FLOPanalyzer.s: src/floatfuncs/FLOPanalyzer.c.s
.PHONY : src/floatfuncs/FLOPanalyzer.s

# target to generate assembly for a file
src/floatfuncs/FLOPanalyzer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/FLOPanalyzer.c.s
.PHONY : src/floatfuncs/FLOPanalyzer.c.s

src/floatfuncs/fdiv.o: src/floatfuncs/fdiv.c.o
.PHONY : src/floatfuncs/fdiv.o

# target to build an object file
src/floatfuncs/fdiv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/fdiv.c.o
.PHONY : src/floatfuncs/fdiv.c.o

src/floatfuncs/fdiv.i: src/floatfuncs/fdiv.c.i
.PHONY : src/floatfuncs/fdiv.i

# target to preprocess a source file
src/floatfuncs/fdiv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/fdiv.c.i
.PHONY : src/floatfuncs/fdiv.c.i

src/floatfuncs/fdiv.s: src/floatfuncs/fdiv.c.s
.PHONY : src/floatfuncs/fdiv.s

# target to generate assembly for a file
src/floatfuncs/fdiv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/fdiv.c.s
.PHONY : src/floatfuncs/fdiv.c.s

src/floatfuncs/fsub.o: src/floatfuncs/fsub.c.o
.PHONY : src/floatfuncs/fsub.o

# target to build an object file
src/floatfuncs/fsub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/fsub.c.o
.PHONY : src/floatfuncs/fsub.c.o

src/floatfuncs/fsub.i: src/floatfuncs/fsub.c.i
.PHONY : src/floatfuncs/fsub.i

# target to preprocess a source file
src/floatfuncs/fsub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/fsub.c.i
.PHONY : src/floatfuncs/fsub.c.i

src/floatfuncs/fsub.s: src/floatfuncs/fsub.c.s
.PHONY : src/floatfuncs/fsub.s

# target to generate assembly for a file
src/floatfuncs/fsub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/fsub.c.s
.PHONY : src/floatfuncs/fsub.c.s

src/floatfuncs/research.o: src/floatfuncs/research.c.o
.PHONY : src/floatfuncs/research.o

# target to build an object file
src/floatfuncs/research.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/research.c.o
.PHONY : src/floatfuncs/research.c.o

src/floatfuncs/research.i: src/floatfuncs/research.c.i
.PHONY : src/floatfuncs/research.i

# target to preprocess a source file
src/floatfuncs/research.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/research.c.i
.PHONY : src/floatfuncs/research.c.i

src/floatfuncs/research.s: src/floatfuncs/research.c.s
.PHONY : src/floatfuncs/research.s

# target to generate assembly for a file
src/floatfuncs/research.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/floatfuncs.dir/build.make CMakeFiles/floatfuncs.dir/src/floatfuncs/research.c.s
.PHONY : src/floatfuncs/research.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perftest.dir/build.make CMakeFiles/perftest.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perftest.dir/build.make CMakeFiles/perftest.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perftest.dir/build.make CMakeFiles/perftest.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SimpleDB"
	@echo "... floatfuncs"
	@echo "... perftest"
	@echo "... src/SimpleDB/simpledb.o"
	@echo "... src/SimpleDB/simpledb.i"
	@echo "... src/SimpleDB/simpledb.s"
	@echo "... src/floatfuncs/FLOPanalyzer.o"
	@echo "... src/floatfuncs/FLOPanalyzer.i"
	@echo "... src/floatfuncs/FLOPanalyzer.s"
	@echo "... src/floatfuncs/fdiv.o"
	@echo "... src/floatfuncs/fdiv.i"
	@echo "... src/floatfuncs/fdiv.s"
	@echo "... src/floatfuncs/fsub.o"
	@echo "... src/floatfuncs/fsub.i"
	@echo "... src/floatfuncs/fsub.s"
	@echo "... src/floatfuncs/research.o"
	@echo "... src/floatfuncs/research.i"
	@echo "... src/floatfuncs/research.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

